pipeline {
    agent any
    environment {
        PORT = 8082
        AWS_REGION = 'eu-west-2'  // specify your AWS region
        ECR_REPO = 'collins-cap-demo-app'  // replace with your ECR repository URL
        IMAGE_TAG = "${env.BUILD_ID}"
    }
    stages {
        stage('Clone Repository') {
            steps {
                git url: 'https://gitlab.com/cloud-devops-assignments/spring-boot-react-example.git'
            }
        }
        
        stage('Build Application') {
            steps {
                echo 'Building the application...'
                sh 'mvn clean install'
            }
        }
        
        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'
                sh """
                docker build -t ${ECR_REPO}:${IMAGE_TAG} .
                """
            }
        }
        
        stage('Push to ECR') {
            steps {
                echo 'Pushing Docker image to ECR...'
                withCredentials([usernamePassword(credentialsId: 'aws-ecr-creds', usernameVariable: 'AWS_ACCESS_KEY_ID', passwordVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                    sh """
                    aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REPO}
                    docker push ${ECR_REPO}:${IMAGE_TAG}
                    """
                }
            }
        }
        
        stage('Deploy to ECS') {
            steps {
                echo 'Deploying to ECS...'
                withCredentials([usernamePassword(credentialsId: 'aws-ecr-creds', usernameVariable: 'AWS_ACCESS_KEY_ID', passwordVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                    sh """
                    aws ecs update-service --cluster your-cluster-name --service your-service-name \
                    --force-new-deployment --region ${AWS_REGION}
                    """
                }
            }
        }
    }
    
    post {
        always {
            echo "Jenkins pipeline completed. The application is deployed to ECS."
        }
    }
}
