stages:
  - build
  - test
  - publish
  - dockerize

variables:
  IMAGE_TAG: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build --configuration Release

test:
  stage: test
  script:
    - dotnet test

publish:
  stage: publish
  script:
    - dotnet publish -c Release -o out

dockerize:
  stage: dockerize
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - main  # Change this to your default branch
